libKOS.o: libKOS.cc \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../testoptions.h \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../include/syscalls.h \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../include/kostypes.h
pthread.o: pthread.cc \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../testoptions.h \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../include/syscalls.h \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../include/kostypes.h \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../include/pthread.h \
 /home/ugd/bjpfannm/JamesKos/457assignment4/src/ulib/../include/syscalls.h
